### ISSUE TITLE
Error!

### ISSUE THREAD

**Issue by alr86** [abhishekmj303/ulauncher-playerctl#1]
[https://www.uplooder.net/img/image/93/5945b6c9b83d80c36d4cb1161fd78565/UlauncherPreferences----2023-06-24-11-54-55.jpg](url)

**Comment by abhishekmj303** [comment]
@alr86 I am not able to reproduce this issue. Did you try restarting ulauncher or reinstalling it?
If it still persists try starting ulauncher from terminal verbosely `ulauncher -v` and send the logs.

**Comment by abhishekmj303** [comment]
Closing as no update from author
